# CMake generated Testfile for 
# Source directory: /Users/anshi/clawd/minllama
# Build directory: /Users/anshi/clawd/minllama/build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(smoke "/Users/anshi/clawd/minllama/build-release/test_smoke")
set_tests_properties(smoke PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;104;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(quant "/Users/anshi/clawd/minllama/build-release/test_quant")
set_tests_properties(quant PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;109;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(loader "/Users/anshi/clawd/minllama/build-release/test_loader")
set_tests_properties(loader PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;113;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(metadata "/Users/anshi/clawd/minllama/build-release/test_metadata")
set_tests_properties(metadata PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;118;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(tensors "/Users/anshi/clawd/minllama/build-release/test_tensors")
set_tests_properties(tensors PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;123;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(tensor_data "/Users/anshi/clawd/minllama/build-release/test_tensor_data")
set_tests_properties(tensor_data PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;128;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(tensor_read "/Users/anshi/clawd/minllama/build-release/test_tensor_read")
set_tests_properties(tensor_read PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;133;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(q40_decode "/Users/anshi/clawd/minllama/build-release/test_q40_decode")
set_tests_properties(q40_decode PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;138;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(matvec "/Users/anshi/clawd/minllama/build-release/test_matvec")
set_tests_properties(matvec PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;143;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(ops "/Users/anshi/clawd/minllama/build-release/test_ops")
set_tests_properties(ops PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;148;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(quant_blocks "/Users/anshi/clawd/minllama/build-release/test_quant_blocks")
set_tests_properties(quant_blocks PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;153;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(rope "/Users/anshi/clawd/minllama/build-release/test_rope")
set_tests_properties(rope PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;158;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(attention_math "/Users/anshi/clawd/minllama/build-release/test_attention_math")
set_tests_properties(attention_math PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;163;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(attention_simd_kernels "/Users/anshi/clawd/minllama/build-release/test_attention_simd_kernels")
set_tests_properties(attention_simd_kernels PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;168;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(attention_single_head "/Users/anshi/clawd/minllama/build-release/test_attention_single_head")
set_tests_properties(attention_single_head PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;173;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(kv_cache "/Users/anshi/clawd/minllama/build-release/test_kv_cache")
set_tests_properties(kv_cache PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;178;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(transformer_layer "/Users/anshi/clawd/minllama/build-release/test_transformer_layer")
set_tests_properties(transformer_layer PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;183;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(transformer_layer_ffn "/Users/anshi/clawd/minllama/build-release/test_transformer_layer_ffn")
set_tests_properties(transformer_layer_ffn PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;188;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(transformer_model "/Users/anshi/clawd/minllama/build-release/test_transformer_model")
set_tests_properties(transformer_model PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;193;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(transformer_logits "/Users/anshi/clawd/minllama/build-release/test_transformer_logits")
set_tests_properties(transformer_logits PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;198;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(greedy "/Users/anshi/clawd/minllama/build-release/test_greedy")
set_tests_properties(greedy PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;203;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(generate "/Users/anshi/clawd/minllama/build-release/test_generate")
set_tests_properties(generate PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;208;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(tokenizer "/Users/anshi/clawd/minllama/build-release/test_tokenizer")
set_tests_properties(tokenizer PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;213;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(generate_text "/Users/anshi/clawd/minllama/build-release/test_generate_text")
set_tests_properties(generate_text PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;218;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(model_loader "/Users/anshi/clawd/minllama/build-release/test_model_loader")
set_tests_properties(model_loader PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;223;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(tokenizer_loader "/Users/anshi/clawd/minllama/build-release/test_tokenizer_loader")
set_tests_properties(tokenizer_loader PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;228;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(cli_args "/Users/anshi/clawd/minllama/build-release/test_cli_args")
set_tests_properties(cli_args PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;233;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(generate_eos "/Users/anshi/clawd/minllama/build-release/test_generate_eos")
set_tests_properties(generate_eos PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;238;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(sampling "/Users/anshi/clawd/minllama/build-release/test_sampling")
set_tests_properties(sampling PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;243;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(generate_sampling "/Users/anshi/clawd/minllama/build-release/test_generate_sampling")
set_tests_properties(generate_sampling PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;248;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(cli_args_sampling "/Users/anshi/clawd/minllama/build-release/test_cli_args_sampling")
set_tests_properties(cli_args_sampling PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;253;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(sampling_topk_topp "/Users/anshi/clawd/minllama/build-release/test_sampling_topk_topp")
set_tests_properties(sampling_topk_topp PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;258;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(cli_args_topk_topp "/Users/anshi/clawd/minllama/build-release/test_cli_args_topk_topp")
set_tests_properties(cli_args_topk_topp PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;263;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(cli_args_debug_tokens "/Users/anshi/clawd/minllama/build-release/test_cli_args_debug_tokens")
set_tests_properties(cli_args_debug_tokens PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;268;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(attention_gqa "/Users/anshi/clawd/minllama/build-release/test_attention_gqa")
set_tests_properties(attention_gqa PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;273;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(attention_gqa_reference "/Users/anshi/clawd/minllama/build-release/test_attention_gqa_reference")
set_tests_properties(attention_gqa_reference PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;278;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(transformer_layer_gqa "/Users/anshi/clawd/minllama/build-release/test_transformer_layer_gqa")
set_tests_properties(transformer_layer_gqa PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;283;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(compare_logits "/Users/anshi/clawd/minllama/build-release/test_compare_logits")
set_tests_properties(compare_logits PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;298;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(bpe_tokenizer "/Users/anshi/clawd/minllama/build-release/test_bpe_tokenizer")
set_tests_properties(bpe_tokenizer PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;307;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(weight_layout_token_embedding "/Users/anshi/clawd/minllama/build-release/test_weight_layout_token_embedding")
set_tests_properties(weight_layout_token_embedding PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;324;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
add_test(matvec_orientation "/Users/anshi/clawd/minllama/build-release/test_matvec_orientation")
set_tests_properties(matvec_orientation PROPERTIES  _BACKTRACE_TRIPLES "/Users/anshi/clawd/minllama/CMakeLists.txt;329;add_test;/Users/anshi/clawd/minllama/CMakeLists.txt;0;")
